/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ski_blade_FrameProcessor */

#ifndef _Included_ski_blade_FrameProcessor
#define _Included_ski_blade_FrameProcessor
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class ski_blade_FrameProcessor_CameraCallbacks */

#ifndef _Included_ski_blade_FrameProcessor_CameraCallbacks
#define _Included_ski_blade_FrameProcessor_CameraCallbacks
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class ski_blade_FrameProcessor_NativeProcessor */

#ifndef _Included_ski_blade_FrameProcessor_NativeProcessor
#define _Included_ski_blade_FrameProcessor_NativeProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ski_blade_FrameProcessor_NativeProcessor
 * Method:    blade
 * Signature: ([BIILski/blade/Barcode;)I
 */
JNIEXPORT jint JNICALL Java_ski_blade_FrameProcessor_00024NativeProcessor_blade
  (JNIEnv *, jobject, jbyteArray, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class ski_blade_FrameProcessor_NativeProcessor_MsgHandler */

#ifndef _Included_ski_blade_FrameProcessor_NativeProcessor_MsgHandler
#define _Included_ski_blade_FrameProcessor_NativeProcessor_MsgHandler
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class ski_blade_FrameProcessor_OnBarcodeFound */

#ifndef _Included_ski_blade_FrameProcessor_OnBarcodeFound
#define _Included_ski_blade_FrameProcessor_OnBarcodeFound
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class ski_blade_FrameProcessor_ProcessorOptions */

#ifndef _Included_ski_blade_FrameProcessor_ProcessorOptions
#define _Included_ski_blade_FrameProcessor_ProcessorOptions
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class ski_blade_FrameProcessor_SensorCallbacks */

#ifndef _Included_ski_blade_FrameProcessor_SensorCallbacks
#define _Included_ski_blade_FrameProcessor_SensorCallbacks
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class ski_blade_FrameProcessor_Status */

#ifndef _Included_ski_blade_FrameProcessor_Status
#define _Included_ski_blade_FrameProcessor_Status
#ifdef __cplusplus
extern "C" {
#endif
#undef ski_blade_FrameProcessor_Status_NOT_FOUND
#define ski_blade_FrameProcessor_Status_NOT_FOUND 0L
#undef ski_blade_FrameProcessor_Status_DETECTED
#define ski_blade_FrameProcessor_Status_DETECTED 1L
#undef ski_blade_FrameProcessor_Status_DECODING_FAILED
#define ski_blade_FrameProcessor_Status_DECODING_FAILED 2L
#undef ski_blade_FrameProcessor_Status_DECODED
#define ski_blade_FrameProcessor_Status_DECODED 3L
#undef ski_blade_FrameProcessor_Status_ERROR
#define ski_blade_FrameProcessor_Status_ERROR -1L
#undef ski_blade_FrameProcessor_Status_ENDED
#define ski_blade_FrameProcessor_Status_ENDED -2L
#ifdef __cplusplus
}
#endif
#endif
